Repository FinFellows/web, pull requests merged in 2024-01, with the labels that each got.

#16 Feat/#1 header, footer 상세 설정 및 디자인 시스템 토큰 업데이트
  .eslintrc.json
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  src/app/globals.css
  src/app/layout.tsx
  src/components/organisms/footer/Footer.tsx
  src/components/organisms/header/Header.tsx
  src/components/organisms/header/MenuItem.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/header.css
  src/stories/page.css
  src/styles/variables-dark.css
  src/styles/variables-light.css
  src/tokens/dark.json
  src/tokens/light.json
  tailwind.config.ts
  tsconfig.json
Labels: 🖼 Html&UI, 🏒 Chore

#17 Feat: #12 마이페이지 UI Component 생성
  src/app/mypage/page.tsx
  src/components/atom/button/MainBtn.tsx
  src/components/atom/button/SubBtn.tsx
  src/components/atom/header/HeaderSwitch.tsx
  src/components/atom/toggle/StudyToggle.tsx
  src/components/molecules/mypage/PolicyItem.tsx
  src/components/organisms/header/Header.tsx
  src/components/organisms/header/MenuItem.tsx
  src/components/organisms/myPage/Accordian.tsx
  src/components/organisms/myPage/LearnWithUs.tsx
  src/components/organisms/myPage/SubHeader.tsx
  src/components/organisms/myPage/ThankYou.tsx
  src/components/organisms/myPage/WhatToDo.tsx
  src/components/templates/myPage/Favorites.tsx
  src/components/templates/myPage/Setting.tsx
  src/public/icons/arrow-down.svg
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/header.css
  src/stories/page.css
  src/styles/variables-dark.css
Labels: 🎇 Feature, 🖼 Html&UI

#34 Feat/#14 반응형 크기 수정
  package-lock.json
  src/hooks/custom/useFinMediaQuery.ts
  tailwind.config.ts
Labels: 🏒 Chore

#40 Feat/#14 금융 뭐하지 API 연동
  next.config.js
  src/api/cmaApi.ts
  src/api/depositsApi.ts
  src/api/financial-productsApi.ts
  src/api/savingsApi.ts
  src/app/financial-products/_components/CmaGuide.tsx
  src/app/financial-products/_components/DepositSavingGuide.tsx
  src/app/financial-products/_components/InterestRateGuide.tsx
  src/app/financial-products/cma/[id]/page.tsx
  src/app/financial-products/cma/page.tsx
  src/app/financial-products/deposits/[id]/page.tsx
  src/app/financial-products/deposits/page.tsx
  src/app/financial-products/savings/[id]/page.tsx
  src/app/financial-products/savings/page.tsx
  src/components/atom/button/BankIconBtn.tsx
  src/components/atom/button/BankIconBtnBig.tsx
  src/components/molecules/rope/Rope.tsx
  src/components/molecules/rope/RopeCma.tsx
  src/components/molecules/whattodo/Cma.tsx
  src/components/molecules/whattodo/DepositSaving.tsx
  src/components/organisms/filter/Filter.tsx
  src/components/organisms/whattodo/MoreBankModal.tsx
  src/components/organisms/whattodo/MoreCmaModal.tsx
  src/public/icons/bubble-p.svg
  src/public/icons/bubble-t.svg
  src/types/financial-productsTypes.ts
Labels: 🔭 API

#57 Feat/#14
  src/app/financial-products/_components/CmaGuide.tsx
  src/app/financial-products/_components/CmaInfoGuide.tsx
  src/app/financial-products/cma/[id]/page.tsx
  src/app/financial-products/cma/page.tsx
  src/app/financial-products/deposits/[id]/page.tsx
  src/app/financial-products/deposits/page.tsx
  src/app/financial-products/savings/[id]/page.tsx
  src/app/financial-products/savings/page.tsx
  src/components/molecules/inputfield/InputAmount.tsx
  src/components/organisms/filter/Filter.tsx
  src/components/organisms/whattodo/MoreBankModal.tsx
  src/components/organisms/whattodo/MoreCmaModal.tsx
  src/styles/globals.css
  src/types/financial-productsTypes.ts
Labels: 🎇 Feature, 🖼 Html&UI, 🔭 API

#63 Feat/#14
  src/api/depositsApi.ts
  src/app/financial-products/_components/CmaInfoGuide.tsx
  src/app/financial-products/_components/InterestRateGuide.tsx
  src/app/financial-products/cma/page.tsx
  src/app/financial-products/deposits/[id]/page.tsx
  src/app/financial-products/deposits/page.tsx
  src/app/financial-products/savings/[id]/page.tsx
  src/app/financial-products/savings/page.tsx
  src/components/atom/button/PaginationBtn.tsx
  src/components/molecules/inputfield/InputAmount.tsx
  src/components/molecules/pagination/Pagination.tsx
  src/components/organisms/filter/Filter.tsx
  src/styles/globals.css
  src/types/financial-productsTypes.ts
Labels: 🎇 Feature, 🖼 Html&UI, 🔭 API

#71 Feat 14: cma 북마크 api 수정
  src/api/bookmarkApi.ts
  src/app/financial-products/cma/[id]/page.tsx
  src/app/financial-products/cma/page.tsx
Labels: 🔭 API

#77 Feat/#14 Feat/#8
  src/api/bookmarkApi.ts
  src/api/policyApi.ts
  src/api/policylistapi/policydetail.tsx
  src/api/policylistapi/policylistapi.tsx
  src/app/financial-products/_components/CmaInfoGuide.tsx
  src/app/financial-products/_components/InterestRateGuide.tsx
  src/app/financial-products/deposits/[id]/page.tsx
  src/app/globals.css
  src/app/policies/[id]/page.tsx
  src/app/policies/page.tsx
  src/components/molecules/Policy/Policy.tsx
  src/components/molecules/Policy/PolicyContent.tsx
  src/components/molecules/Policy/PolicyHeadLine.tsx
  src/components/molecules/SearchFieldForPolicy.tsx
  src/types/financial-productsTypes.ts
  src/types/policyTypes.ts
Labels: 🎇 Feature, 🐞 BugFix, 🏒 Chore, 🔭 API

#80 Feat: 금융 고마워 사진 위치 크기 수정
  src/components/molecules/Policy/Policy.tsx
  src/components/molecules/Policy/PolicyHeadLine.tsx
Labels: 🖼 Html&UI

#88 Feat/#14
  src/app/(learn)/educations/[id]/page.tsx
  src/app/(learn)/educations/page.tsx
  src/components/molecules/Education/EducationContent.tsx
  src/components/molecules/Education/EducationHeadLine.tsx
  src/components/molecules/Education/EducationList.tsx
  src/components/molecules/Education/dummydata.json
  src/components/molecules/Policy/Policy.tsx
Labels: 🔭 API
